---
name: "Check Licenses"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

concurrency:
  group: "check-licenses-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  check-licenses:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout license-checker-action
        uses: actions/checkout@v6
        with:
          repository: 'DFlowProtocol/license-checker-action'
          token: ${{ secrets.LICENSE_AUDIT_PAT_TOKEN }}
          path: './.github/actions/license-checker'

      # syft depends on populated dependency cache
      # in order to build the SBOM

      # rust
      - name: Setup the rust toolchain
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Restore rust dependency cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: check-licenses-${{ runner.os }}-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('Cargo.lock') }}

      - name: Check licenses
        uses: ./.github/actions/license-checker
        continue-on-error: true
        with:
          allowed-licenses: ${{ vars.LICENSE_AUDIT_ALLOWED_LICENSES }}
          comment-on-failure: "false"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          license-audit-api-key: ${{ secrets.LICENSE_AUDIT_API_KEY }}
          license-audit-api-url: ${{ secrets.LICENSE_AUDIT_API_URL }}
          license-overrides: ${{ vars.LICENSE_AUDIT_LICENSE_OVERRIDES }}
          rust-crate-directories: |
            ${{ github.workspace }}
